pipeline {
    agent {
        docker {
            image 'node:22-alpine'
            reuseNode true
            args '-u 0:0 -v /home/jenkinsci/pnpm-store:/root/.pnpm-store'
        }
    }
    environment {
        NEXT_PUBLIC_BACKEND_URL="http://localhost:5000"
    }
    stages {
        stage('Config pnpm') {
            steps {
		sh 'npm i -g pnpm'
                sh 'pnpm config set store-dir /root/.pnpm-store'
            }
        }
        stage('Install dependencies') {
            steps {
                sh 'pnpm i --frozen-lockfile'
            }
        }
        stage('Build Nextjs project') {
            steps {
                sh 'pnpm run build'
            }
        }
    }
    post {
        always {
            sh 'rm -rf node_modules'
            sh 'rm -rf .next'
        }
    }
}

