import {
  AlertTriangle,
  CheckCircle,
  CheckCircle2,
  CheckSquare,
  Circle,
  Clock,
  Cog,
  FileText,
  Flag,
  FolderOpen,
  GitBranch,
  Link,
  Loader2,
  Play,
  PlusCircle,
  Shield,
  Target,
  TrendingDown,
  TrendingUp,
} from "lucide-react";

import {
  BondTypeEnum,
  DeliverablePriorityEnum,
  DeliverableStatusEnum,
  MilestoneStatusEnum,
  ProjectDelayLevelEnum,
  ProjectStatusEnum,
  ProjectTypeEnum,
} from "../_types/project.enums";

// Configuración para ProjectTypeEnum
export const projectTypeConfig = {
  [ProjectTypeEnum.DOCUMENTADO]: {
    label: "Documentado",
    description: "Proyecto completamente documentado",
    className: "bg-blue-200 dark:bg-blue-800/40",
    textClass: "text-blue-900 dark:text-blue-200",
    borderColor: "border-blue-400 dark:border-blue-700",
    hoverClass: "hover:bg-blue-300 dark:hover:bg-blue-700/60",
    icon: FileText,
    badge: "info",
    iconClass: "text-blue-600 dark:text-blue-300",
  },
  [ProjectTypeEnum.HIBRIDO]: {
    label: "Híbrido",
    description: "Proyecto con documentación e implementación mixta",
    className: "bg-purple-200 dark:bg-purple-800/40",
    textClass: "text-purple-900 dark:text-purple-200",
    borderColor: "border-purple-400 dark:border-purple-700",
    hoverClass: "hover:bg-purple-300 dark:hover:bg-purple-700/60",
    icon: GitBranch,
    badge: "secondary",
    iconClass: "text-purple-600 dark:text-purple-300",
  },
  [ProjectTypeEnum.IMPLEMENTADO]: {
    label: "Implementado",
    description: "Proyecto completamente implementado",
    className: "bg-green-200 dark:bg-green-800/40",
    textClass: "text-green-900 dark:text-green-200",
    borderColor: "border-green-400 dark:border-green-700",
    hoverClass: "hover:bg-green-300 dark:hover:bg-green-700/60",
    icon: Cog,
    badge: "success",
    iconClass: "text-green-600 dark:text-green-300",
  },
};

// Configuración para ProjectStatusEnum
export const projectStatusConfig = {
  [ProjectStatusEnum.CREATED]: {
    label: "Creado",
    description: "Proyecto recién creado",
    className: "bg-gray-200 dark:bg-gray-800/40",
    textClass: "text-gray-900 dark:text-gray-200",
    borderColor: "border-gray-400 dark:border-gray-600",
    hoverClass: "hover:bg-gray-300 dark:hover:bg-gray-700/60",
    icon: Circle,
    badge: "neutral",
    iconClass: "text-gray-600 dark:text-gray-300",
  },
  [ProjectStatusEnum.PLANNING]: {
    label: "Planificación",
    description: "Proyecto en fase de planificación",
    className: "bg-blue-200 dark:bg-blue-800/40",
    textClass: "text-blue-900 dark:text-blue-200",
    borderColor: "border-blue-400 dark:border-blue-700",
    hoverClass: "hover:bg-blue-300 dark:hover:bg-blue-700/60",
    icon: Clock,
    badge: "info",
    iconClass: "text-blue-600 dark:text-blue-300",
  },
  [ProjectStatusEnum.IN_PROGRESS]: {
    label: "En Progreso",
    description: "Proyecto actualmente en ejecución",
    className: "bg-yellow-200 dark:bg-yellow-800/40",
    textClass: "text-yellow-900 dark:text-yellow-200",
    borderColor: "border-yellow-400 dark:border-yellow-700",
    hoverClass: "hover:bg-yellow-300 dark:hover:bg-yellow-700/60",
    icon: Play,
    badge: "warning",
    iconClass: "text-yellow-600 dark:text-yellow-300",
  },
  [ProjectStatusEnum.OPERATIONALLY_COMPLETED]: {
    label: "Completado Operacional",
    description: "Proyecto completado desde el punto de vista operacional",
    className: "bg-orange-200 dark:bg-orange-800/40",
    textClass: "text-orange-900 dark:text-orange-200",
    borderColor: "border-orange-400 dark:border-orange-700",
    hoverClass: "hover:bg-orange-300 dark:hover:bg-orange-700/60",
    icon: CheckCircle2,
    badge: "info",
    iconClass: "text-orange-600 dark:text-orange-300",
  },
  [ProjectStatusEnum.OFFICIALLY_COMPLETED]: {
    label: "Completado Oficial",
    description: "Proyecto completado y aprobado oficialmente",
    className: "bg-green-200 dark:bg-green-800/40",
    textClass: "text-green-900 dark:text-green-200",
    borderColor: "border-green-400 dark:border-green-700",
    hoverClass: "hover:bg-green-300 dark:hover:bg-green-700/60",
    icon: CheckCircle2,
    badge: "success",
    iconClass: "text-green-600 dark:text-green-300",
  },
};

// Configuración para MilestoneStatusEnum
export const milestoneStatusConfig = {
  [MilestoneStatusEnum.PLANNING]: {
    label: "Planificación",
    description: "Hito en fase de planificación",
    className: "bg-blue-200 dark:bg-blue-800/40",
    textClass: "text-blue-900 dark:text-blue-200",
    borderColor: "border-blue-400 dark:border-blue-700",
    hoverClass: "hover:bg-blue-300 dark:hover:bg-blue-700/60",
    icon: Clock,
    badge: "info",
    iconClass: "text-blue-600 dark:text-blue-300",
  },
  [MilestoneStatusEnum.VALIDATED]: {
    label: "Validado",
    description: "Hito validado y aprobado",
    className: "bg-indigo-200 dark:bg-indigo-800/40",
    textClass: "text-indigo-900 dark:text-indigo-200",
    borderColor: "border-indigo-400 dark:border-indigo-700",
    hoverClass: "hover:bg-indigo-300 dark:hover:bg-indigo-700/60",
    icon: CheckSquare,
    badge: "secondary",
    iconClass: "text-indigo-600 dark:text-indigo-300",
  },
  [MilestoneStatusEnum.IN_PROGRESS]: {
    label: "En Progreso",
    description: "Hito actualmente en ejecución",
    className: "bg-yellow-200 dark:bg-yellow-800/40",
    textClass: "text-yellow-900 dark:text-yellow-200",
    borderColor: "border-yellow-400 dark:border-yellow-700",
    hoverClass: "hover:bg-yellow-300 dark:hover:bg-yellow-700/60",
    icon: Loader2,
    badge: "warning",
    iconClass: "text-yellow-600 dark:text-yellow-300",
  },
  [MilestoneStatusEnum.OPERATIONALLY_COMPLETED]: {
    label: "Completado Operacional",
    description: "Hito completado desde el punto de vista operacional",
    className: "bg-orange-200 dark:bg-orange-800/40",
    textClass: "text-orange-900 dark:text-orange-200",
    borderColor: "border-orange-400 dark:border-orange-700",
    hoverClass: "hover:bg-orange-300 dark:hover:bg-orange-700/60",
    icon: Target,
    badge: "info",
    iconClass: "text-orange-600 dark:text-orange-300",
  },
  [MilestoneStatusEnum.OFFICIALLY_APPROVED]: {
    label: "Aprobado Oficialmente",
    description: "Hito aprobado oficialmente",
    className: "bg-green-200 dark:bg-green-800/40",
    textClass: "text-green-900 dark:text-green-200",
    borderColor: "border-green-400 dark:border-green-700",
    hoverClass: "hover:bg-green-300 dark:hover:bg-green-700/60",
    icon: Flag,
    badge: "success",
    iconClass: "text-green-600 dark:text-green-300",
  },
};

// Configuración para DeliverableStatusEnum
export const deliverableStatusConfig = {
  [DeliverableStatusEnum.REGISTERED]: {
    label: "Registrado",
    description: "Entregable registrado en el sistema",
    className: "bg-gray-200 dark:bg-gray-800/40",
    textClass: "text-gray-900 dark:text-gray-200",
    borderColor: "border-gray-400 dark:border-gray-600",
    hoverClass: "hover:bg-gray-300 dark:hover:bg-gray-700/60",
    icon: FolderOpen,
    badge: "neutral",
    iconClass: "text-gray-600 dark:text-gray-300",
  },
  [DeliverableStatusEnum.IN_PROCESS]: {
    label: "En Proceso",
    description: "Entregable actualmente en desarrollo",
    className: "bg-yellow-200 dark:bg-yellow-800/40",
    textClass: "text-yellow-900 dark:text-yellow-200",
    borderColor: "border-yellow-400 dark:border-yellow-700",
    hoverClass: "hover:bg-yellow-300 dark:hover:bg-yellow-700/60",
    icon: Loader2,
    badge: "warning",
    iconClass: "text-yellow-600 dark:text-yellow-300",
  },
  [DeliverableStatusEnum.FINISHED]: {
    label: "Finalizado",
    description: "Entregable completado",
    className: "bg-green-200 dark:bg-green-800/40",
    textClass: "text-green-900 dark:text-green-200",
    borderColor: "border-green-400 dark:border-green-700",
    hoverClass: "hover:bg-green-300 dark:hover:bg-green-700/60",
    icon: CheckCircle2,
    badge: "success",
    iconClass: "text-green-600 dark:text-green-300",
  },
};

// Configuración para DeliverablePriorityEnum (excluido por el usuario)
export const deliverablePriorityConfig = {
  [DeliverablePriorityEnum.LOW]: {
    label: "Baja",
    description: "Prioridad baja",
    className: "bg-gray-200 dark:bg-gray-800/40",
    textClass: "text-gray-900 dark:text-gray-200",
    borderColor: "border-gray-400 dark:border-gray-600",
    hoverClass: "hover:bg-gray-300 dark:hover:bg-gray-700/60",
    icon: Circle,
    badge: "neutral",
    iconClass: "text-gray-600 dark:text-gray-300",
  },
  [DeliverablePriorityEnum.MEDIUM]: {
    label: "Media",
    description: "Prioridad media",
    className: "bg-yellow-200 dark:bg-yellow-800/40",
    textClass: "text-yellow-900 dark:text-yellow-200",
    borderColor: "border-yellow-400 dark:border-yellow-700",
    hoverClass: "hover:bg-yellow-300 dark:hover:bg-yellow-700/60",
    icon: AlertTriangle,
    badge: "warning",
    iconClass: "text-yellow-600 dark:text-yellow-300",
  },
  [DeliverablePriorityEnum.HIGH]: {
    label: "Alta",
    description: "Prioridad alta",
    className: "bg-orange-200 dark:bg-orange-800/40",
    textClass: "text-orange-900 dark:text-orange-200",
    borderColor: "border-orange-400 dark:border-orange-700",
    hoverClass: "hover:bg-orange-300 dark:hover:bg-orange-700/60",
    icon: AlertTriangle,
    badge: "info",
    iconClass: "text-orange-600 dark:text-orange-300",
  },
};

// Configuración para BondTypeEnum
export const bondTypeConfig = {
  [BondTypeEnum.INTERNAL]: {
    label: "Interna",
    description: "Aval interno de la empresa",
    className: "bg-blue-200 dark:bg-blue-800/40",
    textClass: "text-blue-900 dark:text-blue-200",
    borderColor: "border-blue-400 dark:border-blue-700",
    hoverClass: "hover:bg-blue-300 dark:hover:bg-blue-700/60",
    icon: Shield,
    badge: "info",
    iconClass: "text-blue-600 dark:text-blue-300",
  },
  [BondTypeEnum.EXTERNAL]: {
    label: "Externa",
    description: "Aval externo de entidad financiera",
    className: "bg-green-200 dark:bg-green-800/40",
    textClass: "text-green-900 dark:text-green-200",
    borderColor: "border-green-400 dark:border-green-700",
    hoverClass: "hover:bg-green-300 dark:hover:bg-green-700/60",
    icon: Shield,
    badge: "success",
    iconClass: "text-green-600 dark:text-green-300",
  },
};

export const precedentDisplayConfig = {
  NO_PRECEDENT_REQUIRED: {
    label: "No requiere precedente",
    icon: CheckCircle,
    className: "bg-green-100 dark:bg-green-900/40",
    textClass: "text-green-700 dark:text-green-400",
    borderColor: "border-green-300 dark:border-green-700",
    iconClass: "text-green-600 dark:text-green-500",
  },
  HAS_PRECEDENT: {
    icon: Link,
    className: "bg-blue-100 dark:bg-blue-900/40",
    textClass: "text-blue-700 dark:text-blue-400",
    borderColor: "border-blue-300 dark:border-blue-700",
    iconClass: "text-blue-600 dark:text-blue-500",
  },
  ASSIGN_PRECEDENT: {
    label: "Asignar precedente",
    icon: PlusCircle,
    // Using muted foreground for a clean, placeholder-like look
    className: "bg-transparent hover:bg-muted/50 border-dashed",
    textClass: "text-muted-foreground",
    borderColor: "border-muted-foreground/60",
    iconClass: "text-muted-foreground/80",
  },
};

// Configuración para ProjectDelayLevelEnum
export const projectDelayLevelConfig = {
  [ProjectDelayLevelEnum.ON_TIME]: {
    label: "En Tiempo",
    description: "Proyecto en tiempo según cronograma",
    className: "bg-green-200 dark:bg-green-800/40",
    textClass: "text-green-900 dark:text-green-200",
    borderColor: "border-green-400 dark:border-green-700",
    hoverClass: "hover:bg-green-300 dark:hover:bg-green-700/60",
    icon: CheckCircle,
    badge: "success",
    iconClass: "text-green-600 dark:text-green-300",
  },
  [ProjectDelayLevelEnum.AHEAD]: {
    label: "Adelantado",
    description: "Proyecto adelantado respecto al cronograma",
    className: "bg-blue-200 dark:bg-blue-800/40",
    textClass: "text-blue-900 dark:text-blue-200",
    borderColor: "border-blue-400 dark:border-blue-700",
    hoverClass: "hover:bg-blue-300 dark:hover:bg-blue-700/60",
    icon: TrendingUp,
    badge: "info",
    iconClass: "text-blue-600 dark:text-blue-300",
  },
  [ProjectDelayLevelEnum.ACCEPTABLE_DELAY]: {
    label: "Retraso Aceptable",
    description: "Proyecto con retraso dentro del rango aceptable",
    className: "bg-yellow-200 dark:bg-yellow-800/40",
    textClass: "text-yellow-900 dark:text-yellow-200",
    borderColor: "border-yellow-400 dark:border-yellow-700",
    hoverClass: "hover:bg-yellow-300 dark:hover:bg-yellow-700/60",
    icon: AlertTriangle,
    badge: "warning",
    iconClass: "text-yellow-600 dark:text-yellow-300",
  },
  [ProjectDelayLevelEnum.CRITICAL_DELAY]: {
    label: "Retraso Crítico",
    description: "Proyecto con retraso crítico que requiere atención",
    className: "bg-red-200 dark:bg-red-800/40",
    textClass: "text-red-900 dark:text-red-200",
    borderColor: "border-red-400 dark:border-red-700",
    hoverClass: "hover:bg-red-300 dark:hover:bg-red-700/60",
    icon: TrendingDown,
    badge: "danger",
    iconClass: "text-red-600 dark:text-red-300",
  },
};
