/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["AppController_getHello"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Iniciar sesión */
    post: operations["AuthController_login_v1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Renovar token de acceso usando token de actualización */
    post: operations["AuthController_refreshToken_v1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cerrar sesión */
    post: operations["AuthController_logout_v1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Obtener información del usuario autenticado */
    get: operations["AuthController_me_v1"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Obtener todos los usuarios */
    get: operations["UsersController_findAll_v1"];
    put?: never;
    /** Crear un nuevo usuario */
    post: operations["UsersController_create_v1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Obtener un usuario por su ID */
    get: operations["UsersController_findById_v1"];
    /** Actualizar un usuario existente */
    put: operations["UsersController_update_v1"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/{id}/permissions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Obtener permisos de un usuario
     * @description Obtiene todos los permisos asignados a un usuario a través de sus roles
     */
    get: operations["UsersController_getUserPermissions_v1"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/roles": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Obtener todos los roles */
    get: operations["RolesController_getRoles_v1"];
    put?: never;
    /** Crear un nuevo rol */
    post: operations["RolesController_createRole_v1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/roles/{roleId}/permissions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Obtener permisos de un rol */
    get: operations["RolesController_getPermissions_v1"];
    put?: never;
    /** Asignar un permiso a un rol */
    post: operations["RolesController_assignPermission_v1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/roles/{roleId}/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Asignar un rol a un usuario */
    post: operations["RolesController_assignRoleToUser_v1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/roles/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Actualizar un rol */
    put: operations["RolesController_updateRole_v1"];
    post?: never;
    /** Eliminar un rol (desactivación lógica) */
    delete: operations["RolesController_deleteRole_v1"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/permissions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Obtener todos los permisos */
    get: operations["PermissionsController_getPermissions_v1"];
    put?: never;
    /** Crear un nuevo permiso */
    post: operations["PermissionsController_createPermission_v1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/services": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Obtener todos los servicios */
    get: operations["ServicesController_getServices_v1"];
    put?: never;
    /** Crear un nuevo servicio */
    post: operations["ServicesController_create_v1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/services/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Actualizar un servicio existente */
    put: operations["ServicesController_update_v1"];
    post?: never;
    /** Eliminar un servicio existente */
    delete: operations["ServicesController_delete_v1"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/objectives": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Crear una nueva objetivo */
    post: operations["ObjectivesController_create_v1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/objectives/{serviceId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Obtener todas las objetivos de un servicio */
    get: operations["ObjectivesController_getObjectivesByServiceId_v1"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/objectives/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Actualizar un objetivo existente */
    put: operations["ObjectivesController_update_v1"];
    post?: never;
    /** Eliminar una objetivo existente */
    delete: operations["ObjectivesController_delete_v1"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/activities": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Obtener actividades por objetivo */
    get: operations["ActivitiesController_getActivitiesByObjectiveId_v1"];
    put?: never;
    /** Crear una nueva actividad */
    post: operations["ActivitiesController_create_v1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/activities/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Actualizar una actividad existente */
    put: operations["ActivitiesController_update_v1"];
    post?: never;
    /** Eliminar una actividad existente */
    delete: operations["ActivitiesController_delete_v1"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/clinics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Obtener todas las clínicas */
    get: operations["ClinicsController_getClinics_v1"];
    put?: never;
    /** Crear una clínica */
    post: operations["ClinicsController_create_v1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/clinics/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Obtener una clínica por ID */
    get: operations["ClinicsController_getClinicById_v1"];
    /** Actualizar una clínica */
    put: operations["ClinicsController_update_v1"];
    post?: never;
    /** Eliminar una clínica */
    delete: operations["ClinicsController_delete_v1"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    SignInDto: {
      /**
       * Format: email
       * @description El email del usuario.
       * @example admin@admin.com
       */
      email: string;
      /**
       * @description La contraseña del usuario
       * @example password
       */
      password: string;
    };
    AuthResponseDto: {
      /**
       * @description Estado HTTP de la respuesta
       * @example 200
       */
      statusCode: number;
      /**
       * @description Mensaje informativo sobre la operación
       * @example Operación realizada con éxito
       */
      message?: string;
      /**
       * @description ID único del usuario
       * @example 5f9d5e7b8e7a6c1d4c8e7a6c
       */
      id?: string;
      /**
       * @description Correo electrónico del usuario
       * @example usuario@ejemplo.com
       */
      email?: string;
      /**
       * @description Nombre completo del usuario
       * @example Juan Pérez
       */
      fullName?: string;
      roles: string[][];
    };
    UserResponseDto: {
      /**
       * @description ID único del usuario
       * @example 5f9d5e7b8e7a6c1d4c8e7a6c
       */
      id: string;
      /**
       * @description Correo electrónico del usuario
       * @example usuario@ejemplo.com
       */
      email: string;
      /**
       * @description Nombre completo del usuario
       * @example Juan Pérez
       */
      fullName: string;
      roles: string[][];
      /**
       * @description Estado del usuario (activo/inactivo)
       * @example true
       */
      isActive: boolean;
      /**
       * Format: date-time
       * @description Fecha de creación del usuario
       * @example 2023-01-15T14:30:00Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description Fecha de última actualización del usuario
       * @example 2023-01-20T10:15:00Z
       */
      updatedAt: string;
    };
    CreateUserDto: {
      /**
       * Format: email
       * @description Correo electrónico del usuario
       * @example usuario@ejemplo.com
       */
      email: string;
      /**
       * @description Contraseña del usuario
       * @example password123
       */
      password: string;
      /**
       * @description Nombre completo del usuario
       * @example Juan Pérez
       */
      fullName: string;
      roleIds: string[][];
    };
    UpdateUserDto: {
      /**
       * Format: email
       * @description Correo electrónico del usuario
       * @example usuario@ejemplo.com
       */
      email?: string;
      /**
       * @description Contraseña del usuario
       * @example password123
       */
      password?: string;
      /**
       * @description Nombre completo del usuario
       * @example Juan Pérez
       */
      fullName?: string;
      roles: string[][];
      /**
       * @description Estado del usuario (activo/inactivo)
       * @example true
       */
      isActive?: boolean;
    };
    PermissionResponseDto: {
      /**
       * @description ID único del permiso
       * @example 5f9d5e7b8e7a6c1d4c8e7a6c
       */
      id: string;
      /**
       * @description Nombre del permiso
       * @example users:create
       */
      name: string;
      /**
       * @description Descripción del permiso
       * @example Permite crear usuarios en el sistema
       */
      description?: string | null;
      /**
       * @description Recurso al que aplica el permiso
       * @example users
       */
      resource: string;
      /**
       * @description Acción que permite el permiso
       * @example create
       */
      action: string;
      /**
       * Format: date-time
       * @description Fecha de creación del permiso
       * @example 2023-01-15T14:30:00Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description Fecha de última actualización del permiso
       * @example 2023-01-20T10:15:00Z
       */
      updatedAt: string;
    };
    CreateRoleDto: {
      /**
       * @description Nombre del rol
       * @example admin
       */
      name: string;
      /**
       * @description Descripción del rol
       * @example Rol de administrador con acceso completo
       */
      description?: string;
      permissionIds: string[][];
    };
    RoleResponseDto: {
      /**
       * @description ID único del rol
       * @example 5f9d5e7b8e7a6c1d4c8e7a6c
       */
      id: string;
      /**
       * @description Nombre del rol
       * @example admin
       */
      name: string;
      /**
       * @description Descripción del rol
       * @example Administrador del sistema con acceso completo
       */
      description?: string | null;
      /**
       * @description IDs de permisos asignados al rol
       * @example [
       *       "5f9d5e7b8e7a6c1d4c8e7a6c",
       *       "5f9d5e7b8e7a6c1d4c8e7a6d"
       *     ]
       */
      permissionIds?: string[];
      /**
       * @description Estado del rol (activo/inactivo)
       * @example true
       */
      isActive: boolean;
      /**
       * Format: date-time
       * @description Fecha de creación del rol
       * @example 2023-01-15T14:30:00Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description Fecha de última actualización del rol
       * @example 2023-01-20T10:15:00Z
       */
      updatedAt: string;
    };
    AssignPermissionDto: {
      /**
       * @description The ID of the permission to assign
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      permissionId: string;
    };
    AssignRoleToUserDto: {
      /**
       * @description The ID of the user to assign the role to
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      userId: string;
    };
    UpdateRoleDto: {
      /**
       * @description Nombre del rol
       * @example super-admin
       */
      name?: string;
      /**
       * @description Descripción del rol
       * @example Rol con acceso ampliado a todas las funciones
       */
      description?: string;
      permissionIds: string[][];
    };
    CreatePermissionDto: {
      /**
       * @description The name of the permission
       * @example users:create
       */
      name: string;
      /**
       * @description The description of the permission
       * @example Create a new user
       */
      description?: string;
      /**
       * @description The resource of the permission
       * @example users
       */
      resource: string;
      /**
       * @description The action of the permission
       * @example create
       */
      action: string;
    };
    CreateServiceDto: {
      /**
       * @description El nombre del servicio
       * @example Servicio de ejemplo
       */
      name: string;
      /**
       * @description La descripción del servicio
       * @example Descripción del servicio de ejemplo
       */
      description?: string;
      /**
       * @description Los objetivos del servicio
       * @example [
       *       "Objetivo 1",
       *       "Objetivo 2"
       *     ]
       */
      objectives?: string[];
    };
    ServiceResponseDto: {
      /**
       * @description El ID del servicio
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      id: string;
      /**
       * @description El nombre del servicio
       * @example Servicio de ejemplo
       */
      name: string;
      /**
       * @description La descripción del servicio
       * @example Descripción del servicio de ejemplo
       */
      description?: string;
      objectives: string[][];
      /**
       * @description El estado del servicio
       * @example true
       */
      isActive: boolean;
    };
    UpdateServiceDto: {
      /**
       * @description El nombre del servicio
       * @example Servicio 1
       */
      name?: string;
      /**
       * @description La descripción del servicio
       * @example Descripción del servicio
       */
      description?: string;
      /**
       * @description Los objetivos del servicio
       * @example [
       *       "Objetivo 1",
       *       "Objetivo 2"
       *     ]
       */
      objectives?: string[];
    };
    CreateObjectiveDto: {
      /**
       * @description Nombre de la objetivo
       * @example Objetivo de ejemplo
       */
      name: string;
      /**
       * @description Descripción de la objetivo
       * @example Descripción de la objetivo
       */
      description?: string;
      /**
       * @description ID del servicio al que pertenece la objetivo
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      serviceId: string;
      /**
       * @description Actividades de la objetivo
       * @example [
       *       "123e4567-e89b-12d3-a456-426614174000"
       *     ]
       */
      activities?: string[];
    };
    ObjectiveResponseDto: {
      /**
       * @description ID de la objetivo
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      id: string;
      /**
       * @description Nombre de la objetivo
       * @example Objetivo de ejemplo
       */
      name: string;
      /**
       * @description Descripción de la objetivo
       * @example Descripción de la objetivo
       */
      description?: string;
      /**
       * @description ID del servicio al que pertenece la objetivo
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      serviceId: string;
      /**
       * @description Actividades de la objetivo
       * @example [
       *       "123e4567-e89b-12d3-a456-426614174000"
       *     ]
       */
      activities?: string[];
    };
    UpdateObjectiveDto: {
      /**
       * @description El nombre del objetivo
       * @example Objetivo 1
       */
      name?: string;
      /**
       * @description La descripción del objetivo
       * @example Descripción del objetivo 1
       */
      description?: string;
      /**
       * @description El ID del servicio al que pertenece el objetivo
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      serviceId?: string;
    };
    CreateActivityDto: {
      /**
       * @description El nombre de la actividad
       * @example Activity 1
       */
      name: string;
      /**
       * @description La descripción de la actividad
       * @example Descripción de la actividad
       */
      description?: string;
      /**
       * @description Si necesita evidencia de la actividad
       * @example true
       */
      evidenceRequired?: boolean;
      /**
       * @description El ID del objetivo al que pertenece la actividad
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      objectiveId?: string;
    };
    ActivityResponseDto: {
      /**
       * @description El ID de la actividad
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      id: string;
      /**
       * @description El nombre de la actividad
       * @example Activity 1
       */
      name: string;
      /**
       * @description La descripción de la actividad
       * @example Descripción de la actividad
       */
      description: string;
      /**
       * @description Si la actividad requiere evidencia
       * @example true
       */
      evidenceRequired: boolean;
      /**
       * @description El ID del objetivo al que pertenece la actividad
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      objectiveId: string;
    };
    UpdateActivityDto: {
      /**
       * @description El nombre de la actividad
       * @example Activity 1
       */
      name?: string;
      /**
       * @description La descripción de la actividad
       * @example Descripción de la actividad
       */
      description?: string;
      /**
       * @description Si la actividad requiere evidencia
       * @example true
       */
      evidenceRequired?: boolean;
      /**
       * @description ID del objetivo al que pertenece la actividad
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      objectiveId?: string;
    };
    CreateClinicDto: {
      /**
       * @description RUC de la clínica
       * @example 12345678901
       */
      ruc: string;
      /**
       * @description Nombre de la clínica
       * @example Clínica de Salud
       */
      name: string;
      /**
       * @description Dirección de la clínica
       * @example Calle Principal 123
       */
      address: string;
      /**
       * @description Teléfono de la clínica
       * @example 1234567890
       */
      phone: string;
      /**
       * Format: email
       * @description Correo electrónico de la clínica
       * @example clinica@gmail.com
       */
      email: string;
      /**
       * @description Contraseña de la clínica
       * @example 1234567890
       */
      password: string;
      /**
       * @description Departamento de la clínica
       * @example Lima
       */
      department: string;
      /**
       * @description Provincia de la clínica
       * @example Lima
       */
      province: string;
      /**
       * @description Distrito de la clínica
       * @example Miraflores
       */
      district: string;
    };
    ClinicResponseDto: {
      /**
       * @description ID de la clínica
       * @example 12345678901
       */
      id: string;
      /**
       * @description RUC de la clínica
       * @example 12345678901
       */
      ruc: string;
      /**
       * @description Nombre de la clínica
       * @example Clínica de Salud
       */
      name: string;
      /**
       * @description Dirección de la clínica
       * @example Calle Principal 123
       */
      address: string;
      /**
       * @description Teléfono de la clínica
       * @example 1234567890
       */
      phone: string;
      /**
       * @description Correo electrónico de la clínica
       * @example clinica@gmail.com
       */
      email: string;
      /**
       * @description Departamento de la clínica
       * @example Lima
       */
      department: string;
      /**
       * @description Provincia de la clínica
       * @example Lima
       */
      province: string;
      /**
       * @description Distrito de la clínica
       * @example Lima
       */
      district: string;
      /**
       * @description Estado de la clínica
       * @example true
       */
      isActive: boolean;
    };
    UpdateClinicDto: {
      /**
       * @description Nombre de la clínica
       * @example Clínica de Salud
       */
      name?: string;
      /**
       * @description Dirección de la clínica
       * @example Calle Principal 123
       */
      address?: string;
      /**
       * @description Teléfono de la clínica
       * @example 1234567890
       */
      phone?: string;
      /**
       * @description Correo electrónico de la clínica
       * @example clinica@gmail.com
       */
      email?: string;
      /**
       * @description Contraseña de la clínica
       * @example 1234567890
       */
      password?: string;
      /**
       * @description Departamento de la clínica
       * @example Lima
       */
      department?: string;
      /**
       * @description Provincia de la clínica
       * @example Lima
       */
      province?: string;
      /**
       * @description Distrito de la clínica
       * @example Lima
       */
      district?: string;
      /**
       * @description Estado de la clínica
       * @example true
       */
      isActive?: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AppController_getHello: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string;
        };
      };
    };
  };
  AuthController_login_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignInDto"];
      };
    };
    responses: {
      /** @description Devuelve los datos del usuario autenticado y establece cookies para los tokens */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResponseDto"];
        };
      };
    };
  };
  AuthController_refreshToken_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Renueva el token de acceso y actualiza las cookies */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResponseDto"];
        };
      };
    };
  };
  AuthController_logout_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Sesión cerrada exitosamente y cookies eliminadas */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResponseDto"];
        };
      };
    };
  };
  AuthController_me_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Devuelve la información del usuario autenticado */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResponseDto"];
        };
      };
    };
  };
  UsersController_findAll_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Lista de usuarios */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponseDto"][];
        };
      };
    };
  };
  UsersController_create_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUserDto"];
      };
    };
    responses: {
      /** @description Usuario creado con éxito */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponseDto"];
        };
      };
      /** @description Datos inválidos o usuario ya existe */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_findById_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Usuario encontrado */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponseDto"];
        };
      };
      /** @description Usuario no encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_update_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateUserDto"];
      };
    };
    responses: {
      /** @description Usuario actualizado con éxito */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponseDto"];
        };
      };
      /** @description Usuario no encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_getUserPermissions_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Permisos obtenidos exitosamente */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PermissionResponseDto"][];
        };
      };
      /** @description Usuario no encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error interno del servidor */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RolesController_getRoles_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Lista de roles */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RoleResponseDto"][];
        };
      };
    };
  };
  RolesController_createRole_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateRoleDto"];
      };
    };
    responses: {
      /** @description Rol creado exitosamente */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RoleResponseDto"];
        };
      };
    };
  };
  RolesController_getPermissions_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        roleId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Lista de permisos del rol */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PermissionResponseDto"][];
        };
      };
    };
  };
  RolesController_assignPermission_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        roleId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AssignPermissionDto"];
      };
    };
    responses: {
      /** @description Permiso asignado exitosamente */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RolesController_assignRoleToUser_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        roleId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AssignRoleToUserDto"];
      };
    };
    responses: {
      /** @description Rol asignado exitosamente al usuario */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RolesController_updateRole_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateRoleDto"];
      };
    };
    responses: {
      /** @description Rol actualizado exitosamente */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RoleResponseDto"];
        };
      };
    };
  };
  RolesController_deleteRole_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Rol eliminado exitosamente */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No se puede eliminar el rol (ya está inactivo o está asignado a usuarios) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Rol no encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PermissionsController_getPermissions_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Lista de permisos */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PermissionsController_createPermission_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePermissionDto"];
      };
    };
    responses: {
      /** @description Permiso creado exitosamente */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ServicesController_getServices_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Lista de servicios */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceResponseDto"][];
        };
      };
    };
  };
  ServicesController_create_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateServiceDto"];
      };
    };
    responses: {
      /** @description El servicio ha sido creado exitosamente */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceResponseDto"];
        };
      };
    };
  };
  ServicesController_update_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateServiceDto"];
      };
    };
    responses: {
      /** @description El servicio ha sido actualizado exitosamente */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceResponseDto"];
        };
      };
    };
  };
  ServicesController_delete_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description El servicio ha sido eliminado exitosamente */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ObjectivesController_create_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateObjectiveDto"];
      };
    };
    responses: {
      /** @description Objetivo creado con éxito */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ObjectiveResponseDto"];
        };
      };
    };
  };
  ObjectivesController_getObjectivesByServiceId_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        serviceId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Lista de objetivos */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ObjectiveResponseDto"][];
        };
      };
    };
  };
  ObjectivesController_update_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateObjectiveDto"];
      };
    };
    responses: {
      /** @description Objetivo actualizado con éxito */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ObjectiveResponseDto"];
        };
      };
    };
  };
  ObjectivesController_delete_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Objetivo eliminado con éxito */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ActivitiesController_getActivitiesByObjectiveId_v1: {
    parameters: {
      query: {
        /** @description ID del objetivo para filtrar actividades */
        objectiveId: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Las actividades han sido obtenidas correctamente */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ActivityResponseDto"][];
        };
      };
    };
  };
  ActivitiesController_create_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateActivityDto"];
      };
    };
    responses: {
      /** @description La actividad ha sido creada correctamente */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ActivityResponseDto"];
        };
      };
    };
  };
  ActivitiesController_update_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateActivityDto"];
      };
    };
    responses: {
      /** @description La actividad ha sido actualizada correctamente */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ActivityResponseDto"];
        };
      };
    };
  };
  ActivitiesController_delete_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description La actividad ha sido eliminada correctamente */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ClinicsController_getClinics_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Clínicas obtenidas exitosamente */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ClinicResponseDto"][];
        };
      };
    };
  };
  ClinicsController_create_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateClinicDto"];
      };
    };
    responses: {
      /** @description Clínica creada exitosamente */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ClinicResponseDto"];
        };
      };
    };
  };
  ClinicsController_getClinicById_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Clínica obtenida exitosamente */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ClinicResponseDto"];
        };
      };
    };
  };
  ClinicsController_update_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateClinicDto"];
      };
    };
    responses: {
      /** @description Clínica actualizada exitosamente */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ClinicResponseDto"];
        };
      };
    };
  };
  ClinicsController_delete_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Clínica eliminada exitosamente */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
