---
- name: Setup target machine
  become: false
  hosts: all
  vars:
    #
    # -- required --
    #
    remote_folder: "{{ _remote_folder }}"

  tasks:
    - name: Ensure target directory exists
      file:
        path: "{{ remote_folder }}"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

